config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires, only: [:new, :create]
  resources :corps
  resources :areas, only: [:index, :show]
  mount RuCaptcha::Engine => "/rucaptcha"

  get 'corp' => 'corps#new'
  get 'school' => 'schools#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  root 'questionnaires#new'
  namespace :admin do
    resources :users
    resources :categories
    resources :provinces
    resources :schools
    resources :questionnaires, only: [:index]
    resources :corps, only: [:index]
    root 'questionnaires#index'
  end
  resource :profile, only: [:show, :update] do
    collection do
      get :settings
    end
  end

end

app/models/school.rb
# == Schema Information
#
# Table name: schools
#
#  id          :integer          not null, primary key
#  name        :string
#  province_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_schools_on_province_id  (province_id)
#

class School < ActiveRecord::Base
  belongs_to :province
  validates_presence_of :name, :province_id
end

app/controllers/admin/schools_controller.rb
class Admin::SchoolsController < Admin::BaseController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  def index
    @schools = School.includes(:province).all
  end

  def edit

  end

  def new
    @school = School.new
  end

  def create
    @school = School.new(school_params)

    if @school.save
      redirect_to admin_schools_path, notice: '成功增加学校。'
    else
      render :new
    end
  end

  def update
    if @school.update(school_params)
      redirect_to admin_schools_path, notice: '成功修改学校。'
    else
      render :edit
    end
  end

  def destroy
    @school.destroy
    redirect_to admin_schools_url, notice: '学校已删除。'
  end

  private
    def set_school
      @school = School.find(params[:id])
    end

    def school_params
      params.require(:school).permit(:name, :province_id)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  layout false
  def index
  end
end

app/views/admin/schools/_form.html.slim
= simple_form_for([:admin,@school], html:{ class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
  = f.error_notification
  .row
    .form-inputs
      = f.input :name
      = f.association :province, include_blank: false
    .col-md-12.form-actions
      = f.button :submit

app/views/admin/schools/_school.html.slim
tr
  td = school.province.name 
  td = school.name
  td = link_to "编辑", edit_admin_school_path(school)
  td = link_to '删除', [:admin, school], data: {:confirm => '确定要删除吗?'}, :method => :delete

app/views/admin/schools/edit.html.slim
== render 'form'

app/views/admin/schools/index.html.slim
- if @schools.present?
  table.table.table-bordered.table-hover.table-stripped
    thead
      tr
        th 省份
        th 院校名称
        th 编辑
        th 删除
    tbody
      = render @schools
    
== link_to "增加院校", new_admin_school_path, class: "btn btn-primary"

app/views/admin/schools/new.html.slim
== render 'form'