config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires, only: [:new, :create]
  resources :corps
  resources :areas, only: [:index, :show]
  mount RuCaptcha::Engine => "/rucaptcha"

  get 'corp' => 'corps#new'
  get 'school' => 'schools#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  root 'questionnaires#new'
  namespace :admin do
    resources :users
    resources :categories
    resources :provinces
    resources :schools
    resources :questionnaires, only: [:index]
    resources :corps, only: [:index]
    root 'questionnaires#index'
  end
  resource :profile, only: [:show, :update] do
    collection do
      get :settings
    end
  end

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  order_no   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  validates :name,  presence: true
  validates :order_no, numericality: { only_integer: true }, uniqueness: true
  has_many :questions
  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_catetory, only: [:show, :edit, :update, :destroy]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: '成功创建大题。'
    else
      render 'new'
    end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: '成功修改大题。'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_path, notice: '大题已删除。'
  end

  private
    def set_catetory
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :order_no, questions_attributes: [:id, :name, :field_type, :category_id, :required, :question_no, :_destroy])
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_category.html.slim
tr
  td = category.name
  td = category.order_no
  td = link_to "编辑", edit_admin_category_path(category)
  td = link_to '删除', [:admin, category], data: {:confirm => '确定要删除吗?'}, :method => :delete

app/views/admin/categories/_form.html.slim
= simple_form_for([:admin,@category], html:{ class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
  = f.error_notification
  .row
    .form-inputs
      = f.input :name
      = f.input :order_no
  .row
    .col-md-6 
      h4 名称
    .col-md-2
      h4 题号
    .col-md-2
      h4 类型
    .col-md-2
      h4 删除
  #questions
    = f.simple_fields_for :questions do |question|
      = render 'question_fields', f: question
  .col-md-12.links
    = link_to_add_association '增加问题', f, :questions,{ class: 'btn btn-primary' }
  .col-md-12.form-actions
    = f.button :submit

app/views/admin/categories/_question_fields.html.slim
.nested-fields.question.row
  .col-md-6
    = f.text_field :name, class: "form-control"
  .col-md-2
    = f.text_field :question_no, class: "form-control"
  .col-md-2
    = f.select :field_type, options_for_select({"频率五选一" => 'rythem', "符合三选一" => 'conform3', 
                            "符合五选一" => 'conform5', "时间八选一" => 'time8', 
                            "符合四选一" => 'conform4', "进步四选一" => "progress4",
                            "满意六选一" => 'satisfy6', "认同五选一" => "agree5", 
                            "同意六选一" => "agree6"}, :selected => f.object.field_type), {include_blank: false}, {class: 'form-control'}
  .col-md-2
    = link_to_remove_association "删除问题", f,{ class: 'btn btn-danger' }

app/views/admin/categories/create.html.slim
h1 Admin::Categories#create
p Find me in app/views/admin/categories/create.html.slim

app/views/admin/categories/index.html.slim
- if @categories.present?
  table.table.table-bordered.table-hover.table-stripped
    thead
      tr
        th 题目
        th 顺序号
        th 编辑
        th 删除
    tbody
      = render @categories
    
== link_to "新建大题", new_admin_category_path, class: "btn btn-primary"