config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires, only: [:new, :create]
  resources :corps
  resources :areas, only: [:index, :show]
  mount RuCaptcha::Engine => "/rucaptcha"

  get 'corp' => 'corps#new'
  get 'school' => 'schools#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  root 'questionnaires#new'
  namespace :admin do
    resources :users
    resources :categories
    resources :provinces
    resources :schools
    resources :questionnaires, only: [:index]
    resources :corps, only: [:index]
    root 'questionnaires#index'
  end
  resource :profile, only: [:show, :update] do
    collection do
      get :settings
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  name            :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_username  (username) UNIQUE
#

class User < ActiveRecord::Base
  before_save { self.username = username.downcase }
  validates :username,  presence: true, length: { maximum: 50 }, uniqueness: true
  has_secure_password
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def edit

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: '成功创建用户。'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: '成功修改用户。'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: '用户已删除。'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :name, :password, :password_confirmation)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.slim
= simple_form_for([:admin,@user], html:{ class: 'form-horizontal' }, wrapper: :horizontal_form) do |f|
  = f.error_notification
  
  .form-inputs
    = f.input :username
    = f.input :name
    = f.input :password
    = f.input :password_confirmation
  .form-actions
    = f.button :submit

app/views/admin/users/_user.html.slim
tr
  td = user.username
  td = user.name
  td = link_to "编辑", edit_admin_user_path(user)
  td = link_to '删除', [:admin, user], data: {:confirm => '确定要删除吗?'}, :method => :delete

app/views/admin/users/index.html.slim
table.table.table-bordered.table-hover.table-stripped
  thead
    tr
      th 用户名
      th 姓名
      th 编辑
      th 删除
  tbody
    = render @users
    
== link_to "新建用户", new_admin_user_path, class: "btn btn-primary"