config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires, only: [:new, :create]
  resources :corps
  resources :areas, only: [:index, :show]
  mount RuCaptcha::Engine => "/rucaptcha"

  get 'corp' => 'corps#new'
  get 'school' => 'schools#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  root 'questionnaires#new'
  namespace :admin do
    resources :users
    resources :categories
    resources :provinces
    resources :schools
    resources :questionnaires, only: [:index]
    resources :corps, only: [:index]
    root 'questionnaires#index'
  end
  resource :profile, only: [:show, :update] do
    collection do
      get :settings
    end
  end

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "学生问卷", root_path, {target: "_blank"} %></li>
        <li><%= link_to "企业问卷", new_corp_path, {target: "_blank"} %></li>
        <% if logged_in? %>
          <li><%= link_to "省份", admin_provinces_path %></li>
          <li><%= link_to "院校", admin_schools_path %></li>
          <li><%= link_to "学生问卷题目", admin_categories_path %></li>
          <li><%= link_to "学生结果", admin_questionnaires_path %></li>
          <li><%= link_to "企业结果", admin_corps_path %></li>
          <li><%= link_to "学生结果csv", admin_root_path(format: "csv") %></li>
          <li><%= link_to "企业结果csv", admin_corps_path(format: "csv") %></li>
          <li><%= link_to "退出", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "登录", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_message.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Survey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <%= render 'layouts/message' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/layouts/frontend.html.slim
doctype html
html
  head
    title 问卷调查
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    div.container
      = render 'layouts/message'
      == yield
      = debug(params) if Rails.env.development? 